openBackhaul/MicroWaveDeviceInventory

MicroWaveDeviceInventory+services.yaml

add mwdi entries to latest serviceList template

update serviceList (Fixes #20)

---

MicroWaveDeviceInventory+profileInstances.yaml

updated uuids with ownAppId
removed all instances except for default actionProfile instances

Updates ProfileInstancesList (Fixes #22)

---

MicroWaveDeviceInventory+profiles.yaml

No profiles other than ActionProfile needed for the moment (removed other entries)

Update ProfileList Fixes #21

---

spec/MicroWaveDeviceInventory+services.yaml

Update ServiceList to latest AppPattern changes

---

spec/MicroWaveDeviceInventory+profileInstances.yaml

Update profileInstanceList fix linting issues

---

spec/MicroWaveDeviceInventory+profileInstances.yaml

Update profileInstanceList due to pattern update

---

spec/MicroWaveDeviceInventory+services.yaml

Update serviceList with new operation-name keyword

---

spec/MicroWaveDeviceInventory.yaml

Add mwdi-services to oas: parameters

---

spec/MicroWaveDeviceInventory.yaml

Add parsed mwdi-services to oas: paths

---

spec/MicroWaveDeviceInventory+config.json
spec/MicroWaveDeviceInventory+forwardings.yaml

Update config file from template

---

spec/MicroWaveDeviceInventory+services.yaml

Update wrong uuids in serviceList nr-opclient

---

spec/MicroWaveDeviceInventory+forwardings.yaml
spec/MicroWaveDeviceInventory+services.yaml

Add db indexAlias, remove handover entries

---

spec/MicroWaveDeviceInventory+services.yaml

merge already done changes for #83
mwdi-1-0-0 shall only have a couple of services and needs to be changed overall.
(#83 may not have been finished, new ticket will be opened)

Add MWDI db initialization parts in spec

---

README.md

Update MWDI description page

---

spec/MicroWaveDeviceInventory+services.yaml
spec/MicroWaveDeviceInventory.yaml

Adds A2LT services to spec (fixes #111)

Kmohr-soprasteria/issue111

---

spec/MicroWaveDeviceInventory+forwardings.yaml
spec/MicroWaveDeviceInventory+services.yaml
spec/MicroWaveDeviceInventory.yaml

[Code] Change operation names to use "-"

---

spec/MicroWaveDeviceInventory+forwardings.yaml
spec/MicroWaveDeviceInventory+services.yaml
spec/MicroWaveDeviceInventory.yaml

adds 2 new notification services

Kmohr-soprasteria/issue127

---

spec/MicroWaveDeviceInventory+forwardings.yaml

[Code] Update ForwardingList for v1.0.0 for LTP changes

---

spec/MicroWaveDeviceInventory+config.json

[Code] Update CONFIGfile for forwarding localids

---

spec/MicroWaveDeviceInventory.yaml

[Code] Shrink response codes section in OAS

---

spec/MicroWaveDeviceInventory.yaml

[Code] prepare OAS service is-000 (without callback)

---

spec/MicroWaveDeviceInventory.yaml

[Code] Correct uuids in AppPattern part of OAS

---

spec/MicroWaveDeviceInventory+config.json
spec/MicroWaveDeviceInventory+forwardings.yaml
spec/MicroWaveDeviceInventory+services.yaml
spec/MicroWaveDeviceInventory.yaml

[Code] Correct Controller version number in OAS

---

spec/MicroWaveDeviceInventory+config.json
spec/MicroWaveDeviceInventory+services.yaml

[Code] update elasticSearch index

---

spec/MicroWaveDeviceInventory+config.json
spec/MicroWaveDeviceInventory+forwardings.yaml
spec/MicroWaveDeviceInventory+services.yaml

[Code] Update paths for requests to the Controller

---

spec/MicroWaveDeviceInventory+forwardings.yaml
spec/MicroWaveDeviceInventory+services.yaml

[Code] What parts of CC to retrieve (config only?): provide config+nonconfig

---

spec/MicroWaveDeviceInventory+config.json
spec/MicroWaveDeviceInventory+forwardings.yaml
spec/MicroWaveDeviceInventory+services.yaml
spec/MicroWaveDeviceInventory.yaml
spec/_forwardings_and_callbacks_wip_temp/1_forwardings/00x_forwardings_draft.yaml
spec/_forwardings_and_callbacks_wip_temp/3_callbacks/Ziel = Controller/003_callback.yaml
spec/diagrams/other-process-flows/controlflow_no_forwarding_ControllerNotification.plantuml

Kmohr-soprasteria/issue223

---

spec/MicroWaveDeviceInventory+config.json
spec/MicroWaveDeviceInventory+profileInstances.yaml

[Code] Neues IntegerProfile für DeviceSync

---

spec/MicroWaveDeviceInventory+config.json
spec/MicroWaveDeviceInventory+profileInstances.yaml
spec/MicroWaveDeviceInventory+profiles.yaml

[Code] Align profileInstances for cyclic CC retrieval operation with MATR

---

spec/MicroWaveDeviceInventory+config.json
spec/MicroWaveDeviceInventory+services.yaml

[Code] add subscriber-http-client info to config file

---

spec/diagrams/200_CacheControlConstruct.plantuml

[Code] Correct 200_diagram

---

spec/MicroWaveDeviceInventory+forwardings.yaml
spec/MicroWaveDeviceInventory.yaml

Add top-level-equipment

---

spec/MicroWaveDeviceInventory.yaml

Correct UUIDs by prefix MountName

---

spec/MicroWaveDeviceInventory+services.yaml

Merge review changes to serviceList

Kmohr-soprasteria/issue309

---

spec/MicroWaveDeviceInventory+config.json
spec/MicroWaveDeviceInventory+forwardings.yaml
spec/MicroWaveDeviceInventory+services.yaml
spec/MicroWaveDeviceInventory.yaml

(backup branch created before merging)

Kmohr-soprasteria/issue316

---

spec/MicroWaveDeviceInventory.yaml

Add parameters /v1/regard-device-alarm callbacks

---

spec/MicroWaveDeviceInventory.yaml

additionalProperties:false property to be added for the action-profile schema of core-model-1-4:control-construct

---

spec/MicroWaveDeviceInventory.yaml

string-profile schema : enumeration type to be updated

---

server/service/individualServices/CyclicProcessService/cyclicProcess.js

First Commit

---

server/service/individualServices/cacheUpdateBuilder.js

to Change implementation for CacheUpdateBuilder

---

server/service/individualServices/cacheResponseBuilder.js
server/service/individualServices/cacheUpdateBuilder.js

to modify Cache builder and updater

---

server/service/IndividualServicesService.js
spec/MicroWaveDeviceInventory+profiles.yaml

Assignees: @nardecchia-siae
Labels: implementation
Fixes #395

To finalize first version

---

server/dockerfile

remove proxy reference from dockerfile

---

server/service/individualServices/cacheUpdateBuilder.js

To fix an Issue with ES update in case of live filtered queries

---

server/service/IndividualServicesService.js

to implement service: /core-model-1-4:network-control-domain=cache/control-construct={mount-name}/alarms-1-0:alarm-pac/alarm-capability

---

server/service/IndividualServicesService.js

to implement service: /core-model-1-4:network-control-domain=cache/control-construct={mount-name}/alarms-1-0:alarm-pac/alarm-configuration

---

server/service/IndividualServicesService.js

to implement service: /core-model-1-4:network-control-domain=cache/control-construct={mount-name}/alarms-1-0:alarm-pac/current-alarms

---

server/service/IndividualServicesService.js

to implement service: /core-model-1-4:network-control-domain=cache/control-construct={mount-name}/alarms-1-0:alarm-pac/alarm-event-records

---

server/service/IndividualServicesService.js

to implement service: /core-model-1-4:network-control-domain=live/control-construct={mount-name}/alarms-1-0:alarm-pac/alarm-capability

---

server/service/IndividualServicesService.js

to implement service: /core-model-1-4:network-control-domain=live/control-construct={mount-name}/alarms-1-0:alarm-pac/alarm-configuration

---

server/service/IndividualServicesService.js

to implement service: /core-model-1-4:network-control-domain=live/control-construct={mount-name}/alarms-1-0:alarm-pac/current-alarms

---

server/service/IndividualServicesService.js

to implement service: /core-model-1-4:network-control-domain=live/control-construct={mount-name}/alarms-1-0:alarm-pac/alarm-event-records

---

server/service/IndividualServicesService.js

to implement service: /core-model-1-4:network-control-domain=cache/control-construct={mount-name}/firmware-1-0:firmware-collection

---

server/service/IndividualServicesService.js

to implement service: /core-model-1-4:network-control-domain=cache/control-construct={mount-name}/profile-collection

---

server/service/IndividualServicesService.js
server/service/individualServices/cacheUpdateBuilder.js

to implement service: /core-model-1-4:network-control-domain=live/control-construct={mount-name}/firmware-1-0:firmware-collection

---

spec/MicroWaveDeviceInventory.yaml

Correct operationIds, remove dublicate parameter

---

server/service/IndividualServicesService.js

Added fixes to some api's

---

server/api/openapi.yaml
server/service/IndividualServicesService.js
server/service/individualServices/cacheResponseBuilder.js
server/service/individualServices/cacheUpdateBuilder.js

Response body should match the schema defined in the specification

---

server/service/IndividualServicesService.js

to implement service: /core-model-1-4:network-control-domain=cache/control-construct={mount-name}/profile-collection/profile={uuid}

---

server/service/IndividualServicesService.js

to implement service: /core-model-1-4:network-control-domain=cache/control-construct={mount-name}/logical-termination-point={uuid}

---

server/service/IndividualServicesService.js

to implement service: /v1/provide-list-of-device-interfaces

---

server/service/IndividualServicesService.js

to implement service: /v1/provide-list-of-actual-device-equipment

---

server/service/IndividualServicesService.js

Fixes #621
Fixes #622
Fixes #623
Fixes #624
Fixes #625
Fixes #626
Fixes #627
Fixes #628

to implement service: /core-model-1-4:network-control-domain=live/control-construct={mount-name}/profile-collection

---

server/service/IndividualServicesService.js

Fixes #650
Fixes #651
Fixes #652
Fixes #653

to implement service: /core-model-1-4:network-control-domain=live/control-construct={mount-name}/logical-termination-point={uuid}

---

server/service/IndividualServicesService.js

Fixes #676
Fixes #677
Fixes #678
Fixes #679
Fixes #680
Fixes #681
Fixes #682
Fixes #683
Fixes #684
Fixes #685

to implement callback: RequestForLiveHybridMwStructureHistoricalPerformancesCausesReadingFromDeviceAndWritingIntoCache

---

server/service/IndividualServicesService.js

Fixes #696
Fixes #697
Fixes #698
Fixes #699
Fixes #700
Fixes #701
Fixes #702
Fixes #703
Fixes #704
Fixes #705
Fixes #706
Fixes #707

to implement callback: RequestForLivePureEthernetStructureCapabilityCausesReadingFromDeviceAndWritingIntoCache

---

server/service/IndividualServicesService.js
server/service/individualServices/cacheUpdateBuilder.js
server/service/individualServices/rest/client/Client.js

Response provided from cache shall contain real values for uuid/local-id instead of modified values

---

server/service/individualServices/ElasticsearchPreparation.js

Observing parse error when MWDI is trying to get CC for cache

---

server/index.js
server/package.json
server/service/IndividualServicesService.js
server/service/individualServices/cacheResponseBuilder.js

Fix some issues

---

server/index.js
server/service/IndividualServicesService.js
server/service/individualServices/cacheResponseBuilder.js

Fix an issue with CC read from live

---

server/controllers/IndividualServices.js
server/service/IndividualServicesService.js

to implement service: /v1/regard-device-attribute-value-change

---

server/controllers/IndividualServices.js
server/package-lock.json
server/package.json
server/service/IndividualServicesService.js

to implement service: /v1/regard-controller-attribute-value-change

---

server/service/IndividualServicesService.js

Unable to view the UUID, local-id for live control construct

---

server/service/IndividualServicesService.js

to implement service: /v1/regard-device-alarm

---

server/service/IndividualServicesService.js

to implement service: /v1/regard-device-object-creation

---

server/controllers/IndividualServices.js
server/database/load.json
server/service/IndividualServicesService.js

Observing response status as 400 when we tried to GET any data from cache

---

server/controllers/IndividualServices.js

Assignees: @nardecchia-siae
Labels: bug
Fixes #776

TO fix an issue in controller

---

server/controllers/IndividualServices.js
server/service/IndividualServicesService.js

Unable to retrieve the Live data from application

---

server/service/IndividualServicesService.js

to fix return uuids of two APIs

---

server/controllers/BasicServices.js
server/service/IndividualServicesService.js

to implement callback: PromptForEmbeddingCausesSubscribingForNotifications

---

server/controllers/IndividualServices.js
server/service/IndividualServicesService.js
server/service/individualServices/cacheResponseBuilder.js

Cache and Live response are different for firmware APIs

---

spec/MicroWaveDeviceInventory.yaml

Change attribute name resource to object-path for notifications

---

spec/MicroWaveDeviceInventory+config.json
spec/MicroWaveDeviceInventory+forwardings.yaml
spec/MicroWaveDeviceInventory+services.yaml
spec/MicroWaveDeviceInventory.yaml

Change the path for GET-PUT-DELETE link-port

---

spec/MicroWaveDeviceInventory+config.json
testing/MicroWaveDeviceInventory+data.json

Wrong entries in configFile for stringProfiles

---

spec/MicroWaveDeviceInventory+config.json
spec/MicroWaveDeviceInventory+profileInstances.yaml
spec/MicroWaveDeviceInventory+profiles.yaml
testing/MicroWaveDeviceInventory+data.json

[Code] Description in IntegerProfile (later MWDI release)

---

spec/MicroWaveDeviceInventory+config.json
spec/MicroWaveDeviceInventory+forwardings.yaml
spec/MicroWaveDeviceInventory+services.yaml
spec/MicroWaveDeviceInventory.yaml
testing/MicroWaveDeviceInventory+data.json

vlan-interface-historical-performances to be removed from cache and live

---

spec/MicroWaveDeviceInventory.yaml

Add proper examples for cache/link services

---

server/api/openapi.yaml
server/application-data/encrypted-odl-key.json
server/controllers/BasicServices.js
server/index.js
server/service/IndividualServicesService.js
server/service/individualServices/CyclicProcessService/cyclicProcess.js

Fixes #807
Fixes #801
Fixes #802
Fixes #799

Zaia-siae/issue807

---

server/controllers/BasicServices.js
server/service/IndividualServicesService.js

Changed implementation for Controller attribute change

---

server/service/IndividualServicesService.js

To fix an Issue with delete record exported function

---

spec/MicroWaveDeviceInventory+config.json
spec/MicroWaveDeviceInventory+forwardings.yaml
spec/MicroWaveDeviceInventory+services.yaml
spec/MicroWaveDeviceInventory.yaml
testing/MicroWaveDeviceInventory+data.json

Typo in specification of some api

---

spec/MicroWaveDeviceInventory.yaml

Required attributes for /v1/regard-device-object-creation

---

spec/MicroWaveDeviceInventory.yaml

Stringently apply object-path instead of resource at all Notifications related to Devices

---

spec/MicroWaveDeviceInventory.yaml

ControlConstruct needs to be changed to allow for successful validation

---

server/api/openapi.yaml
server/controllers/IndividualServices.js
server/index.js
server/package-lock.json
server/package.json
server/service/IndividualServicesService.js
server/service/individualServices/ConfigConstants.js
server/service/individualServices/ControlConstructUtil.js
server/service/individualServices/ControllerManagement.js
server/service/individualServices/IndividualServicesOperationsMapping.js
server/service/individualServices/InputValidation.js
server/service/individualServices/NotificationConverter.js
server/service/individualServices/NotificationManagement.js
server/service/individualServices/NotificationStreamManagement.js
server/service/individualServices/SubscriberManagement.js
server/service/individualServices/cacheResponseBuilder.js
server/service/individualServices/cacheUpdateBuilder.js

Fixes #855
Fixes #860
Fixes #861
Fixes #856
Fixes #855
Fixes #854
Fixes #850
Fixes #851
Fixes #818
Fixes #798

Observing 500 internal server error with API /core-model-1-4:network-control-domain=cache/link={uuid}/link-port={localId

---

server/api/openapi.yaml
server/controllers/BasicServices.js
server/index.js
server/service/IndividualServicesService.js
server/service/individualServices/cacheResponseBuilder.js

MWDi is accepting all operation key

---

server/service/IndividualServicesService.js
server/service/individualServices/ElasticsearchPreparation.js
server/service/individualServices/IndividualServicesOperationsMapping.js

Device is not removed from cache when device connection-status is changed from connected to connecting

---

server/controllers/BasicServices.js
server/service/IndividualServicesService.js

Error responses inconsistent

---

server/service/IndividualServicesService.js

Optimizing reading device list from odl

---

server/service/individualServices/CyclicProcessService/cyclicProcess.js

MWDI is stopped unexpectedly.

---

server/service/individualServices/CyclicProcessService/cyclicProcess.js

To fix the start of Cyclic process with new index

---

server/service/individualServices/CyclicProcessService/cyclicProcess.js

Observing 'Maximum call stack size exceeded' error while starting MWDI

---

server/service/individualServices/CyclicProcessService/cyclicProcess.js

To change Sleep function implementation

---

spec/MicroWaveDeviceInventory+forwardings.yaml
spec/MicroWaveDeviceInventory.yaml

Add callback PromptForEmbeddingCausesCyclicLoadingOfDeviceStatusFromController to /v1/embed-yourself

---

README.md

Prepare release of spec v1.2.0

---

spec/MicroWaveDeviceInventory+config.json
spec/MicroWaveDeviceInventory+profileInstances.yaml

Add responseProfiles for inform-about-release-history-in-generic-representation

---

spec/MicroWaveDeviceInventory.yaml

Add standard error code section from AppPattern to OAS

---

spec/MicroWaveDeviceInventory+config.json
spec/MicroWaveDeviceInventory+services.yaml

Correct AA authentication service entries

---

testing/MWDI_1.2.1_ConvenienceServices/MWDI_1.2.1+schema/MWDI_1.2.1+json.json
testing/MWDI_1.2.1_ConvenienceServices/MWDI_1.2.1+schema/MWDI_1.2.1+yaml.yaml
testing/MWDI_1.2.1_ConvenienceServices/MWDI_1.2.1+simulator/MWDI_1.2.1+simulator.1.yaml
testing/MWDI_1.2.1_ConvenienceServices/MWDI_1.2.1+simulator/MWDI_1.2.1+simulator.completeness.yaml

Update testcase collection for /v1/provide-list-of-actual-device-equipment

---

server/service/IndividualServicesService.js

This PR fix the issue https://github.com/openBackhaul/MicroWaveDeviceInventory/issues/1057

filtering a equipmentType is empty or undefined 

---

server/controllers/IndividualServices.js
server/database/load.json
server/service/IndividualServicesService.js

Fixes #1070
Fixes #1071
Fixes #1072
Fixes #1073

Implementation for new link services

---

server/service/individualServices/cacheUpdateBuilder.js

Latta-siae/issue1092

---

spec/MicroWaveDeviceInventory+config.json
spec/MicroWaveDeviceInventory+forwardings.yaml
spec/MicroWaveDeviceInventory+profileInstances.yaml
spec/MicroWaveDeviceInventory+services.yaml
spec/MicroWaveDeviceInventory.yaml

Update uuids and release info to spec 1.2.2

---

spec/MicroWaveDeviceInventory+config.json

connectionStatusSyncPeriod and metadataTableRetentionPeriod profile instances are missing from config file

---

spec/MicroWaveDeviceInventory+config.json

 /v1/register-yourself service fails with 500 Internal server Error

---

spec/MicroWaveDeviceInventory.yaml

Request body of /v1/provide-list-of-links and /v1/provide-data-of-all-links shall be updated

---

spec/MicroWaveDeviceInventory+services.yaml

Update MWDI release number and nr/or info

---

spec/_Defne wip/descriptions.md
spec/_Defne wip/input_for_serviceList.txt

Create working directory for Defne in develop branch

---

spec/MicroWaveDeviceInventory.yaml

Update LAYER_PROTOCOL schema as part of CONTROL_CONSTRUCT schema in MWDI

---

testing/__Redouane wip__/info.txt

Create Testcase folder for Redouane

---

spec/MicroWaveDeviceInventory.yaml

Add new oam layer services for new profile RegexPatternMappingProfile

---

spec/MicroWaveDeviceInventory.yaml

Change /v1/provide-device-status-metadata input filtering

---

spec/MicroWaveDeviceInventory+config.json
spec/MicroWaveDeviceInventory+profileInstances.yaml
spec/additionalDescription/CyclicCacheQualityMeasurementProcess.md

Add new integerProfile for managing the cyclic quality measurement process

---

spec/MicroWaveDeviceInventory.yaml

Add new callbacks for qualityMeasurement

---

spec/_Defne wip/diagrams/00w_ProvideCacheQualityStatistics.plantuml
spec/_Defne wip/diagrams/109_ProvideCacheQualityStatistics.plantuml

(QM) Review Defne's diagram for provide-statistics service

---

spec/MicroWaveDeviceInventory+config.json
spec/MicroWaveDeviceInventory+profileInstances.yaml

(Notifications) Create notificationPollingInterval profileInstance

---

README.md

[Refinement] Refine workings of deviceList

---

spec/MicroWaveDeviceInventory.yaml

Apply appPattern changes for Kafka
